const express = require("express");
const cookieParser = require("cookie-parser");
const cors = require("cors");
const path = require("path");
const { authenticate } = require("./middlewares/auth.middleware");
const { getCorsConfig } = require("./config/runtime");

const authRoutes = require("./routes/auth.routes");
const registerRoutes = require("./routes/register.routes");
const groupRoutes = require("./modules/group/group.routes");
const membershipRoutes = require("./modules/membership/membership.routes");
const joinRequestRoutes = require("./modules/joinRequest/joinRequest.routes");
const phaseRoutes = require("./modules/phase/phase.routes");
const eligibilityRoutes = require("./modules/eligibility/eligibility.routes");
const teamRoutes = require("./modules/team/team.routes");
const hubRoutes = require("./modules/hub/hub.routes");
const eventRoutes = require("./modules/event/event.routes");
const eventJoinRequestRoutes = require("./modules/eventJoinRequest/eventJoinRequest.routes");
const eventTeamInvitationRoutes = require("./modules/eventTeamInvitation/eventTeamInvitation.routes");
const onDutyRoutes = require("./modules/onDuty/onDuty.routes");
const auditRoutes = require("./modules/audit/audit.routes");
const systemConfigRoutes = require("./modules/systemConfig/systemConfig.routes");
const leadershipRequestRoutes = require("./modules/leadershipRequest/leadershipRequest.routes");
const groupTierRequestRoutes = require("./modules/groupTierRequest/groupTierRequest.routes");
const teamChangeTierRoutes = require("./modules/teamChangeTier/teamChangeTier.routes");
const teamTargetRoutes = require("./modules/teamTarget/teamTarget.routes");
const groupPointRoutes = require("./modules/groupPoint/groupPoint.routes");
const {getProfile} = require("./getProfiles");

const app = express();

app.use(express.json({ limit: "10mb" }));
app.use(cookieParser());
app.use(cors(getCorsConfig()));
app.use("/uploads", express.static(path.resolve(__dirname, "uploads")));

app.use("/api/auth", authRoutes);
app.use("/api/register", registerRoutes);
app.use("/api/groups", groupRoutes);
app.use("/api/membership", membershipRoutes);
app.use("/api/join-requests", joinRequestRoutes);
app.use("/api/phases", phaseRoutes);
app.use("/api/eligibility", eligibilityRoutes);
app.use("/api/events", eventRoutes);
app.use("/api/teams", teamRoutes);
app.use("/api/hubs", hubRoutes);
app.use("/api/event-groups", teamRoutes);
app.use("/api/event-join-requests", eventJoinRequestRoutes);
app.use("/api/event-group-join-requests", eventJoinRequestRoutes);
app.use("/api/event-team-invitations", eventTeamInvitationRoutes);
app.use("/api/on-duty", onDutyRoutes);
app.use("/api/audit-logs", auditRoutes);
app.use("/api/system-config", systemConfigRoutes);
app.use("/api/leadership-requests", leadershipRequestRoutes);
app.use("/api/group-tier-requests", groupTierRequestRoutes);
app.use("/api/team-change-tier", teamChangeTierRoutes);
app.use("/api/team-targets", teamTargetRoutes);
app.use("/api/group-points", groupPointRoutes);
app.use("/api/profile", authenticate, getProfile);

module.exports = app;
